version: '3'
services:
  app:
    build: ./app
    command: ["flask", "run"]
    depends_on:
      - db
    entrypoint: [ "dockerize", "--wait", "tcp://db:3306", "--timeout", "20s" ]
    environment:
      CONFIG_FILE: development
    ports:
      - "15000:5000"
    volumes:
      - ./app:/code
  db:
    environment:
      MYSQL_ROOT_PASSWORD: root_dev
      MYSQL_DATABASE: dev_db
      MYSQL_USER: dev_user
      MYSQL_PASSWORD: dev_pass
    image: "mysql:5.7"
    ports:
      - "13306:3306"
    volumes:
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
