version: '3'
services:
  app:
    build: .
    volumes:
      - .:/code
    depends_on:
      - db
    entrypoint: [ "dockerize", "--wait", "tcp://db:3306", "--timeout", "20s" ]
    command: ["flask", "run"]
  db:
    image: "mysql:5.7"
    volumes:
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
