version: '3'
services:
  app:
    ports:
      - "15000:5000"
    environment:
      FLASK_ENV: development
  db:
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_dev
      MYSQL_DATABASE: dev_db
      MYSQL_USER: dev_user
      MYSQL_PASSWORD: dev_pass
